version: '3'
services:
  dock:
    image: node:latest
    command: sh -c "npm install; node /opt/code/express.js"
    ports:
      - 8081:8081
    volumes:
      - ./src:/opt/code  
    working_dir: /opt/code
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: 'varitas'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'letmein'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'letmein'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Where our data will be persisted
      - '3306'
    volumes:
      - ./src/db:/var/lib/mysql
